export const users = [
  {
    id: '808f49e4-53a9-4ade-a200-c2d4f3e08302',
    avatarUrl: '/assets/images/avatars/avatar_1.jpg',
    name: 'Clayton Turcotte',
    company: 'Grady - Aufderhar',
    isVerified: true,
    status: 'active',
    role: 'Backend Developer',
  },
  {
    id: '28514d9b-2cae-4c44-add9-3fc133ebf9a1',
    avatarUrl: '/assets/images/avatars/avatar_2.jpg',
    name: 'Beatrice Wehner',
    company: "O'Keefe Inc",
    isVerified: false,
    status: 'active',
    role: 'UI Designer',
  },
  {
    id: 'a54372b4-354e-49f4-8844-647feec94936',
    avatarUrl: '/assets/images/avatars/avatar_3.jpg',
    name: 'Darren Koelpin',
    company: 'Goyette, Doyle and Dibbert',
    isVerified: true,
    status: 'banned',
    role: 'Front End Developer',
  },
  {
    id: 'b160de42-a4fd-49a3-84da-925e29872398',
    avatarUrl: '/assets/images/avatars/avatar_4.jpg',
    name: 'Kyle Hermiston',
    company: "O'Hara Group",
    isVerified: true,
    status: 'banned',
    role: 'Full Stack Developer',
  },
  {
    id: '799f87b7-10ce-4e08-a4c8-140689235345',
    avatarUrl: '/assets/images/avatars/avatar_5.jpg',
    name: 'Jasmine Jones',
    company: 'Quigley Inc',
    isVerified: true,
    status: 'banned',
    role: 'Full Stack Designer',
  },
  {
    id: 'b295d035-7c0e-48e1-9a72-65257258dc26',
    avatarUrl: '/assets/images/avatars/avatar_6.jpg',
    name: 'Rene Fahey',
    company: 'Zboncak, Gottlieb and Huel',
    isVerified: false,
    status: 'banned',
    role: 'Leader',
  },
  {
    id: '86a5a34c-29c9-4747-9243-e5ccb30f8977',
    avatarUrl: '/assets/images/avatars/avatar_7.jpg',
    name: 'Mack Nikolaus',
    company: 'Lesch Inc',
    isVerified: false,
    status: 'banned',
    role: 'Project Manager',
  },
  {
    id: 'bd4813ee-b869-4274-8019-cd5c4899b906',
    avatarUrl: '/assets/images/avatars/avatar_8.jpg',
    name: 'Pamela Flatley I',
    company: 'Swift LLC',
    isVerified: false,
    status: 'banned',
    role: 'Backend Developer',
  },
  {
    id: 'e5f13346-7d8a-4217-b7ef-0937beb66362',
    avatarUrl: '/assets/images/avatars/avatar_9.jpg',
    name: 'Mr. Marty Miller',
    company: 'Schuster Group',
    isVerified: true,
    status: 'active',
    role: 'UI/UX Designer',
  },
  {
    id: '438bd4e6-129b-4961-8797-6d326cae4f5a',
    avatarUrl: '/assets/images/avatars/avatar_10.jpg',
    name: 'Harvey Ziemann',
    company: 'Pacocha Inc',
    isVerified: false,
    status: 'banned',
    role: 'Hr Manager',
  },
  {
    id: 'e7cfc77c-7f16-491d-b0a5-96a0830a4c89',
    avatarUrl: '/assets/images/avatars/avatar_11.jpg',
    name: 'Bethany Cummings',
    company: 'Sawayn - Heidenreich',
    isVerified: true,
    status: 'banned',
    role: 'Full Stack Designer',
  },
  {
    id: '478e5a13-23cc-4775-b848-0dd0beec0149',
    avatarUrl: '/assets/images/avatars/avatar_12.jpg',
    name: 'Wilbert Tremblay',
    company: 'Watsica, Zieme and Murray',
    isVerified: true,
    status: 'banned',
    role: 'Hr Manager',
  },
  {
    id: '45137d4b-0c09-4997-a653-027e07f2e5e0',
    avatarUrl: '/assets/images/avatars/avatar_13.jpg',
    name: "Elbert O'Keefe",
    company: 'Lesch Inc',
    isVerified: true,
    status: 'banned',
    role: 'Full Stack Designer',
  },
  {
    id: '9c480324-5c38-47fc-91b8-8f4cd550bf96',
    avatarUrl: '/assets/images/avatars/avatar_14.jpg',
    name: 'Danielle Ankunding',
    company: 'Dietrich - Bosco',
    isVerified: false,
    status: 'banned',
    role: 'UI Designer',
  },
  {
    id: '8181e286-6091-4903-9185-b56ef38f48df',
    avatarUrl: '/assets/images/avatars/avatar_15.jpg',
    name: 'Lynda Deckow DDS',
    company: 'Schowalter Inc',
    isVerified: true,
    status: 'active',
    role: 'Project Manager',
  },
  {
    id: '318c4847-6a7f-49fd-947c-7a50ab0be937',
    avatarUrl: '/assets/images/avatars/avatar_16.jpg',
    name: 'Jake Schowalter',
    company: 'Reilly, McClure and Bernier',
    isVerified: true,
    status: 'active',
    role: 'Backend Developer',
  },
  {
    id: 'a26891e2-b542-440b-b52a-7a7980129915',
    avatarUrl: '/assets/images/avatars/avatar_17.jpg',
    name: 'Rickey Dibbert',
    company: 'Carroll Inc',
    isVerified: false,
    status: 'active',
    role: 'Leader',
  },
  {
    id: '7809f68f-bf6a-45f0-93aa-a5b36cedc303',
    avatarUrl: '/assets/images/avatars/avatar_18.jpg',
    name: 'Mr. Harold Zboncak',
    company: 'Cole, Goodwin and Wiegand',
    isVerified: true,
    status: 'banned',
    role: 'Backend Developer',
  },
  {
    id: '48a543e8-b533-4dde-91d2-e67bd0ab1131',
    avatarUrl: '/assets/images/avatars/avatar_19.jpg',
    name: 'Lester Ledner III',
    company: 'Keebler Group',
    isVerified: false,
    status: 'banned',
    role: 'UX Designer',
  },
  {
    id: 'e82b821b-7ba6-4cd2-ba83-69108d31c370',
    avatarUrl: '/assets/images/avatars/avatar_20.jpg',
    name: 'Craig Waelchi',
    company: 'Hartmann, Yundt and Ernser',
    isVerified: false,
    status: 'active',
    role: 'Hr Manager',
  },
  {
    id: 'cbc163cf-5611-477a-9bb4-fc9f48fcc3ea',
    avatarUrl: '/assets/images/avatars/avatar_21.jpg',
    name: 'Mack Legros',
    company: 'Douglas and Sons',
    isVerified: true,
    status: 'banned',
    role: 'Leader',
  },
  {
    id: '6a613dec-4e6f-4b07-a6a7-68859fd7f026',
    avatarUrl: '/assets/images/avatars/avatar_22.jpg',
    name: 'Angela Nitzsche',
    company: 'Lindgren - Heidenreich',
    isVerified: true,
    status: 'active',
    role: 'Project Manager',
  },
  {
    id: '224c7531-d48e-4144-8666-24f1dd433b2a',
    avatarUrl: '/assets/images/avatars/avatar_23.jpg',
    name: 'Derek Pagac',
    company: 'Paucek - Thiel',
    isVerified: false,
    status: 'banned',
    role: 'UI Designer',
  },
  {
    id: 'e537fdcc-21db-4716-8f81-16b6ecb6208d',
    avatarUrl: '/assets/images/avatars/avatar_24.jpg',
    name: 'Ramon Upton',
    company: 'Bernhard and Sons',
    isVerified: true,
    status: 'banned',
    role: 'Leader',
  },
];
